language: go

service:
  - docker

go:
  - "1.8"
  - "1.9"
  - "1.10"

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin v1.9.1

script:
  - make

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - env
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - if [ -n $TRAVIS_TAG ] && [ "$TRAVIS_BRANCH" == "master" ]; then make deploy; fi
